#!/usr/local/bin/bash

BAMFILE=$1
DBFILE=$BAMFILE.db

INDEX_SCRIPT=src/script/makedb.py

echo Creating database table...
echo "create table bamfile (name varchar(50), sequence varchar(100) );" | sqlite3 $DBFILE

echo Populating database table...
samtools view $BAMFILE | python $INDEX_SCRIPT $DBFILE

echo Indexing by read name...
echo "create index bamindex on bamfile(name);" | sqlite3 $DBFILE

