#!/usr/local/bin/bash

#########################################
# Set parameters
LMIN=100
LMAX=400
MIN_MAPQ=0
DELTA_WINDOW=0
UNMAPPED_BAM=data/venter/venterResorted_unmapped.bam
CHR_PREFIX=chr
#########################################

ARGNUM=$#
GASVOUT=$1
BAMFILE=$2
FASTAFILE=$3
JARFILE=build/SplitReadGASV.jar

COMMAND="java -jar $JARFILE $GASVOUT $BAMFILE $FASTAFILE \
		$LMIN $LMAX $MIN_MAPQ $UNMAPPED_BAM $CHR_PREFIX \
		$DELTA_WINDOW"

if [ $ARGNUM != 3 ]; then
  echo "usage: srGASV <GASVoutfile> <reads.bam> <reference.fasta>"
else
  $COMMAND
fi

